### ISSUE TITLE
[BUG] VPM CLI cannot be used while the GUI is open

### ISSUE THREAD

**Issue by bdunderscore** [vrchat-community/creator-companion#20]
**Describe the bug**
The VPM CLI fails to start when the GUI is open

**To Reproduce**
1. Open the VPM GUI
2. Run `vpm` from a command line

**Expected behavior**
The VPM CLI should be usable

**Screenshots**

```
> vpm
Unhandled exception. System.IO.IOException: The process cannot access the file 'C:\Users\bd\AppData\Local\VRChatCreatorCompanion\Logs\20221103T173011-log.txt' because it is being used by another process.
   at System.IO.FileSystem.DeleteFile(String fullPath)
   at VRC.PackageManagement.VRCLibLogger.DeleteOldLogFiles() in /home/runner/work/vrc-package-manager/vrc-package-manager/core/vpm-core-lib/VRCLibLogger.cs:line 88
   at VRC.PackageManagement.CLI.Program.Main(String[] args) in /home/runner/work/vrc-package-manager/vrc-package-manager/core/vpm-cli/Program.cs:line 40
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: CLI 0.1.12

**Comment by orels1** [comment]
This has been fixed as a part of 2.1.0
