### ISSUE TITLE
[BUG] VCC crashed when installing unity editor

### ISSUE THREAD

**Issue by 64766C** [vrchat-community/creator-companion#308]
### Describe the bug

I was installing VCC and unity on a clean Windows 11 installation. I started with VCC installation and followed the instructions to install unity hub, logged in to the hub and activated my license. I clicked next in VCC and then clicked install unity editor 2019.something.something.

VCC instantly crashed but it looks like the unity editor did get installed properly. Event viewer had these two errors:

```Application: CreatorCompanion.exe
CoreCLR Version: 6.0.1623.17311
.NET Version: 6.0.16
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at VCCApp.Services.HTTPHandlers.<>c__DisplayClass60_0.<<HandleInstallUnity>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

```
Faulting application name: CreatorCompanion.exe, version: 2.0.0.0, time stamp: 0x641cea1e
Faulting module name: KERNELBASE.dll, version: 10.0.22621.1635, time stamp: 0x61869dd2
Exception code: 0xe0434352
Fault offset: 0x000000000006536c
Faulting process id: 0x0xFE8
Faulting application start time: 0x0x1D99ADC1E966C38
Faulting application path: C:\Users\[removed]\AppData\Local\Programs\VRChat Creator Companion\CreatorCompanion.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ebbd0ada-dbab-4b38-8b0a-46848451112d
Faulting package full name: 
Faulting package-relative application ID: 
```

### To Reproduce

-

### Expected behavior

Not crash

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.1.1

### OS

Windows 11

**Comment by WillyB1337** [comment]
#212
