### ISSUE TITLE
[BUG] Unable to open VCC with error on the event viewer

### ISSUE THREAD

**Issue by anatawa12** [vrchat-community/creator-companion#391]
### Describe the bug

Failed to open project with the following error

```
Application: CreatorCompanion.exe
CoreCLR Version: 6.0.2523.51912
.NET Version: 6.0.25
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: An item with the same key has already been added. Key: lyuma.av3emulator
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at VRC.PackageManagement.Core.Types.Providers.UnityProjectVPMProvider.Refresh()
   at VRC.PackageManagement.Core.Types.Providers.UnityProjectVPMProvider..ctor(String projectPath)
   at VRC.PackageManagement.Core.Types.UnityProject.RefreshProviders()
   at VRC.PackageManagement.Core.Types.UnityProject..ctor(String path)
   at VRC.CreatorCompanion.Core.Projects.SyncWithSettings()
   at VRC.CreatorCompanion.Core.VCCDatabase.Initialize()
   at VCCApp.Program.Setup()
   at VCCApp.Program.Main(String[] args)
```

### To Reproduce

1. double-click VCC
2. open Event Viewer
3. the error is shown

### Expected behavior

Launch VCC successfully OR open error dialog when startup failed

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.2.x (unable to check actual version)

### OS

Windows 11

**Comment by anatawa12** [comment]
Project that has following vpm-manifest.json will cause this problem

[vpm-manifest.json](https://github.com/vrchat-community/creator-companion/files/13622640/vpm-manifest.json)
