### ISSUE TITLE
[BUG] Crashes upon loading

### ISSUE THREAD

**Issue by Rydema** [vrchat-community/creator-companion#485]
### Describe the bug

2024-05-18 14:47:40.728 +01:00 [INF] VRCLibLogger Writing logs to C:\Users\Ry\AppData\Local\VRChatCreatorCompanion\Logs\20240518T144740-b50bc8db80514684abe4f8f2a8a1a227-log.txt
2024-05-18 14:47:40.735 +01:00 [VRB] Starting Creator Companion
2024-05-18 14:47:40.736 +01:00 [VRB] Set working directory to C:\Program Files (x86)\VRChat Creator Companion\
2024-05-18 14:47:40.747 +01:00 [VRB] Launching WebApi @ 5476 and ApiServer @ 5477 at 0:00:00.0484798
2024-05-18 14:47:40.843 +01:00 [INF] VCC version 2.3.1 (main)
2024-05-18 14:47:40.844 +01:00 [INF] Running on Microsoft Windows 11 (10.0.22621.0)
2024-05-18 14:47:40.879 +01:00 [VRB] Setting up VCC discovery at 0:00:00.1816449
2024-05-18 14:47:40.919 +01:00 [VRB] Starting static server at http://localhost:5476/ at 0:00:00.2214561
2024-05-18 14:47:40.927 +01:00 [VRB] Starting VCC API Server at http://localhost:5477/ at 0:00:00.2294393
2024-05-18 14:47:40.931 +01:00 [ERR] Creator Companion crashed: The process cannot access the file because it is being used by another process.
2024-05-18 14:47:40.937 +01:00 [ERR]    at System.Net.HttpListener.AddPrefixCore(String registeredPrefix)
   at System.Net.HttpListener.AddAllPrefixes()
   at System.Net.HttpListener.Start()
   at VCCApp.Services.ApiServer..ctor(String httpListenerPrefix)
   at VCCApp.Program.RunVCC(String[] args)
   at VCCApp.Program.Main(String[] args)

### To Reproduce

Just loading it up

### Expected behavior

Normal load up

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.1

### OS

Windows 11

**Comment by Veynam** [comment]
Im facing the exact same issue, been having this issue ever since i started using VCC. I can confirm that Creator Companion is NOT running in the background
