### ISSUE TITLE
[BUG] The program crashes immediately after launching

### ISSUE THREAD

**Issue by amxtcgr** [vrchat-community/creator-companion#528]
### Describe the bug

2024-09-10 23:29:11.720 +09:00 [INF] VRCLibLogger Writing logs to C:\Users\Administrator\AppData\Local\VRChatCreatorCompanion\Logs\20240910T232911-2c067ee6de4f4cfba100b53dfe36b811-log.txt
2024-09-10 23:29:11.754 +09:00 [VRB] Starting Creator Companion
2024-09-10 23:29:11.755 +09:00 [VRB] Set working directory to D:\临时桌面\VRC模型\VRChat Creator Companion\
2024-09-10 23:29:11.819 +09:00 [VRB] Launching WebApi @ 5476 and ApiServer @ 5477 at 0:00:00.1995003
2024-09-10 23:29:12.256 +09:00 [INF] VCC version 2.3.2 (main)
2024-09-10 23:29:12.714 +09:00 [INF] Running on Microsoft Windows 10.0.18363
2024-09-10 23:29:12.889 +09:00 [VRB] Setting up VCC discovery at 0:00:01.2726666
2024-09-10 23:29:13.206 +09:00 [VRB] Starting static server at http://localhost:5476/ at 0:00:01.5896912
2024-09-10 23:29:13.234 +09:00 [ERR] Creator Companion crashed: 句柄无效。
2024-09-10 23:29:13.271 +09:00 [ERR]    at System.Net.HttpListener.SetupV2Config()
   at System.Net.HttpListener.Start()
   at VCCApp.Services.StaticFileServer.Start(String httpListenerPrefix)
   at VCCApp.Program.RunVCC(String[] args)
   at VCCApp.Program.Main(String[] args)
[20240910T232911-2c067ee6de4f4cfba100b53dfe36b811-log.txt](https://github.com/user-attachments/files/16946592/20240910T232911-2c067ee6de4f4cfba100b53dfe36b811-log.txt)

### To Reproduce

After opening CreatorCompanion.exe, a window pops up showing 'Creator Companion Crashed.'

### Expected behavior

Normal load up

### Related Product

VCC (VRChat Creator Companion)

### Product Version

2.3.2

### OS

Windows 10

**Comment by orels1** [comment]
Do you use some kind of VPN?

We have had experience with some aggressive VPNs blocking VCC from opening ports on a local machine. If you do use one - I would ask you to try to open VCC with it disabled to see if that works

**Comment by orels1** [comment]
This is available in the new VCC 2.4.0 Open Beta
You can download it here: https://vcc.docs.vrchat.com/news/release-2.4.0

**Comment by orels1** [comment]
This is now released to live, you can get the final download here: https://vrcpm.vrchat.cloud/vcc/Builds/2.4.0/VRChat_CreatorCompanion_Setup_2.4.0.exe
